local TESTS = require "tests.tests"
local BOX2D_SCENE_UTILS = require "main.box2d_scenes.utils"
local BOX2D_UTILS = require "box2d.utils"

local monarch = require "monarch.monarch"

function init(self)
    TESTS.run()
    BOX2D_SCENE_UTILS.debug_draw = BOX2D_UTILS.create_debug_draw(0.04)
    BOX2D_SCENE_UTILS.debug_draw:SetFlags(bit.bor(box2d.b2Draw.e_shapeBit,box2d.b2Draw.e_jointBit))

    timer.delay(2,false,function ()
        monarch.show(hash("dominos"))
    end)

    -- msg.post("@system:", "exit", {code = 0})
end

function final(self)
    -- Add finalization code here
    -- Learn more: https://defold.com/manuals/script/
    -- Remove this function if not needed
end

function update(self, dt)

    -- Add update code here
    -- Learn more: https://defold.com/manuals/script/
    -- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
    -- Add message-handling code here
    -- Learn more: https://defold.com/manuals/message-passing/
    -- Remove this function if not needed
end

function on_input(self, action_id, action)
    -- Add input-handling code here. The game object this script is attached to
    -- must have acquired input focus:
    --
    --    msg.post(".", "acquire_input_focus")
    --
    -- All mapped input bindings will be received. Mouse and touch input will
    -- be received regardless of where on the screen it happened.
    -- Learn more: https://defold.com/manuals/input/
    -- Remove this function if not needed
end

function on_reload(self)
    -- Add reload-handling code here
    -- Learn more: https://defold.com/manuals/hot-reload/
    -- Remove this function if not needed
end
